### ISSUE TITLE
Allow custom divider height

### ISSUE THREAD

**Issue by mikenorgate** [Stu142/FreeCAD-Gridfinity-Workbench#10]
It would be great to be able set a custom height for the x and y dividers independently from the total bin height. Having the divider lower can help being able to grab parts that a closely stacked together

In this example, being able to have the y dividers at half height would allow me to get my fingers in to grab the parts in the bin
![image](https://github.com/user-attachments/assets/78643ff2-e288-4282-9850-5b0259773cc4)

**Comment by Stu142** [comment]
Great idea, I've got it mostly working and will be included with the V0.6.0 release probably in the next couple days.

**Comment by Stu142** [comment]
implemented in new release

**Comment by mikenorgate** [comment]
Tried this out today, works great. Thanks for your work
